### ISSUE TITLE
Issue creating Flutter 1 env

### ISSUE THREAD

**Issue by hanskokx** [PixelToast/puro#10]
Did I do something wrong? It's my first go at trying to use Puro to manage an ancient project.

```
$ puro create t4c_old 1.20.2 --log-level=4
[D] FLUTTER_BIN: null
[D] Config: PuroConfig(
      gitExecutable: LocalFile: 'git',
      puroRoot: LocalDirectory: 'C:\Users\hans\.puro',
      homeDir: LocalDirectory: 'C:\Users\hans',
      projectDir: LocalDirectory: 'C:\Users\hans\git-repos\worktrees\t4c\main',
      parentProjectDir: LocalDirectory: 'C:\Users\hans\git-repos\worktrees\t4c\main',
      flutterGitUrl: https://github.com/flutter/flutter.git,
      engineGitUrl: https://github.com/flutter/engine.git,
      releasesJsonUrl: https://storage.googleapis.com/flutter_infra_release/releases/releases_windows.json,
      flutterStorageBaseUrl: https://storage.googleapis.com,
      environmentOverride: null,
      puroBuildsUrl: https://puro.dev/builds,
      buildTarget: PuroBuildTarget.windowsX64,
      enableShims: false,
    )
[D] target: PuroBuildTarget.windowsX64
[D] Platform.executable: C:\Users\hans\.puro\bin\puro.exe
[D] Platform.resolvedExecutable: C:\Users\hans\.puro\bin\puro.exe
[D] Platform.script: file:///C:/Users/hans/.puro/bin/puro.exe
[D] Platform.packageConfig: null
[D] No package root: Platform.packageConfig is null
[D] packageRoot: null
[D] executablePath: c:\users\hans\.puro\bin\puro.exe
[D] scriptPath: c:\users\hans\.puro\bin\puro.exe
[D] scriptExtension: .exe
[D] installationType: PuroInstallationType.distribution
[D] version: 1.2.5
[V] Started waiting for lock on C:\Users\hans\.puro\prefs.json
[V] Waiting for lock on C:\Users\hans\.puro\prefs.json took 1ms
[V] Started waiting for lock on C:\Users\hans\.puro\releases_windows.json
[V] Waiting for lock on C:\Users\hans\.puro\releases_windows.json took 0ms
[V] Creating a new environment in C:\Users\hans\.puro\envs\t4c_old
[V] Started waiting for lock on C:\Users\hans\.puro\envs\t4c_old\update.lock
[V] Waiting for lock on C:\Users\hans\.puro\envs\t4c_old\update.lock took 0ms
[V] Started waiting for lock on C:\Users\hans\.puro\envs\t4c_old\prefs.json
[V] Waiting for lock on C:\Users\hans\.puro\envs\t4c_old\prefs.json took 0ms
[V] Pre-caching engine...
[V] Cloning flutter with shared refs
[D] repository: C:\Users\hans\.puro\envs\t4c_old\flutter
[D] flutterVersion: beta / 1.20.2 / bbfbf1770c
[D] forkRemoteUrl: beta / 1.20.2 / bbfbf1770c
[D] forkRef: null
[D] [git 11952] C:\Users\hans\.puro\shared\flutter> git show bbfbf1770cca2da7c82e887e4e4af910034800b6:bin/internal/engine.version
[D] [git 21888] C:\Users\hans\.puro\shared\flutter> git rev-parse bbfbf1770cca2da7c82e887e4e4af910034800b6
[D] [git 11952] finished with exit code 0 in 88ms
[D] Pre-caching engine 9d5b21729ff53dbf8eadd8bc97e0e30d77abec95
[V] Started checking if dart works
[D] > C:\Users\hans\.puro\shared\caches\9d5b21729ff53dbf8eadd8bc97e0e30d77abec95\dart-sdk\bin\dart.exe --version
[D] git: bbfbf1770cca2da7c82e887e4e4af910034800b6
[D] [git 21888] finished with exit code 0 in 95ms
[V] Started initializing repository
[D] [git 25512] C:\Users\hans\.puro\envs\t4c_old\flutter> git init
[D] dart.exe finished in 47ms
[V] dart.exe: Dart SDK version: 2.9.1 (stable) (Wed Aug 12 12:37:19 2020 +0200) on "windows_x64"

[V] Checking if dart works took 48ms
[D] git: Initialized empty Git repository in C:/Users/hans/.puro/envs/t4c_old/flutter/.git/
[D] [git 25512] finished with exit code 0 in 91ms
[D] [git 13404] C:\Users\hans\.puro\envs\t4c_old\flutter> git remote -v
[D] [git 13404] finished with exit code 0 in 69ms
[D] [git 12420] C:\Users\hans\.puro\envs\t4c_old\flutter> git remote add origin https://github.com/flutter/flutter.git
[D] [git 12420] finished with exit code 0 in 60ms
[V] Started checking out beta / 1.20.2 / bbfbf1770c
[D] [git 28724] C:\Users\hans\.puro\envs\t4c_old\flutter> git fetch --all
[D] git: From https://github.com/flutter/flutter
[D] git:  * [new branch]            115574-android-selection-haptics-feedback-should-respect-android-settings -> origin/115574-android-selection-haptics-feedback-should-respect-android-settings
[D] git:  * [new branch]            121617-edit-command-to-disableenable-analytics-in-new-unified-analytics-package -> origin/121617-edit-command-to-disableenable-analytics-in-new-unified-analytics-package
[D] git:  * [new branch]            3.3                     -> origin/3.3
[D] git:  * [new branch]            3.8.0-10.1              -> origin/3.8.0-10.1
...SNIP!...
[D] git:  * [new tag]               v1.9.7                  -> v1.9.7
[D] [git 28724] finished with exit code 0 in 3880ms
[D] [git 4708] C:\Users\hans\.puro\envs\t4c_old\flutter> git reset
[D] [git 4708] finished with exit code 0 in 80ms
[D] [git 17780] C:\Users\hans\.puro\envs\t4c_old\flutter> git rev-parse --abbrev-ref HEAD
[D] git: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
[D] git: Use '--' to separate paths from revisions, like this:
[D] git: 'git <command> [<revision>...] -- [<file>...]'
[D] git: HEAD
[D] [git 17780] finished with exit code 128 in 169ms
[V] git failed with exit code 128
[D] [git 27348] C:\Users\hans\.puro\envs\t4c_old\flutter> git show-ref refs/heads/beta
[D] [git 27348] finished with exit code 1 in 290ms
[V] git failed with exit code 1
[D] uninstallEnvShims
[D] [git 11948] C:\Users\hans\.puro\envs\t4c_old\flutter> git rev-parse HEAD
[D] git: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
[D] git: Use '--' to separate paths from revisions, like this:
[D] git: 'git <command> [<revision>...] -- [<file>...]'
[D] git: HEAD
[D] [git 11948] finished with exit code 128 in 62ms
[V] git failed with exit code 128
[D] [git 26884] C:\Users\hans\.puro\envs\t4c_old\flutter> git checkout -b beta bbfbf1770cca2da7c82e887e4e4af910034800b6
[D] git: Switched to a new branch 'beta'
[D] [git 26884] finished with exit code 0 in 4114ms
[D] installEnvShims
[V] Updating config at C:\Users\hans\.puro\envs\t4c_old\flutter\.git\info\exclude
[V] Added "bin/cache"
[V] Added "bin/dart"
[V] Added "bin/dart.bat"
[V] Added "bin/flutter"
[V] Added "bin/flutter.bat"
[V] Added "bin/dart.bak"
[V] Added "bin/dart.bat.bak"
[V] Added "bin/flutter.bak"
[V] Added "bin/flutter.bat.bak"
[V] Added "bin/internal/shared.bat"
[V] Added "bin/internal/shared.sh"
[V] Added "bin/internal/update_dart_sdk.ps1"
[V] Added "bin/internal/update_dart_sdk.sh"
[V] Started waiting for lock on C:\Users\hans\.puro\envs\t4c_old\flutter\bin\dart
[V] Waiting for lock on C:\Users\hans\.puro\envs\t4c_old\flutter\bin\dart took 0ms
[V] Started waiting for lock on C:\Users\hans\.puro\envs\t4c_old\flutter\bin\dart
[V] Waiting for lock on C:\Users\hans\.puro\envs\t4c_old\flutter\bin\dart took 1ms
[V] Started waiting for lock on C:\Users\hans\.puro\envs\t4c_old\flutter\bin\flutter
[V] Waiting for lock on C:\Users\hans\.puro\envs\t4c_old\flutter\bin\flutter took 0ms
[V] Started waiting for lock on C:\Users\hans\.puro\envs\t4c_old\flutter\bin\flutter
[V] Waiting for lock on C:\Users\hans\.puro\envs\t4c_old\flutter\bin\flutter took 0ms
[V] Started waiting for lock on C:\Users\hans\.puro\envs\t4c_old\flutter\bin\dart.bat
[V] Waiting for lock on C:\Users\hans\.puro\envs\t4c_old\flutter\bin\dart.bat took 0ms
[V] Started waiting for lock on C:\Users\hans\.puro\envs\t4c_old\flutter\bin\dart.bat
[V] Waiting for lock on C:\Users\hans\.puro\envs\t4c_old\flutter\bin\dart.bat took 0ms
[V] Started waiting for lock on C:\Users\hans\.puro\envs\t4c_old\flutter\bin\flutter.bat
[V] Waiting for lock on C:\Users\hans\.puro\envs\t4c_old\flutter\bin\flutter.bat took 1ms
[V] Started waiting for lock on C:\Users\hans\.puro\envs\t4c_old\flutter\bin\flutter.bat
[V] Waiting for lock on C:\Users\hans\.puro\envs\t4c_old\flutter\bin\flutter.bat took 0ms
[D] [git 31608] C:\Users\hans\.puro\envs\t4c_old\flutter> git update-index --assume-unchanged -- bin/dart bin/dart.bat bin/flutter bin/flutter.bat bin/internal/shared.bat bin/internal/shared.sh bin/internal/update_dart_sdk.ps1 bin/internal/update_dart_sdk.sh
[D] [git 31608] finished with exit code 0 in 215ms
[V] Updating config at C:\Users\hans\.puro\envs\t4c_old\flutter\.git\info\attributes
[V] Added "bin/dart merge=ours"
[V] Added "bin/dart.bat merge=ours"
[V] Added "bin/flutter merge=ours"
[V] Added "bin/flutter.bat merge=ours"
[V] Added "bin/internal/shared.bat merge=ours"
[V] Added "bin/internal/shared.sh merge=ours"
[V] Added "bin/internal/update_dart_sdk.ps1 merge=ours"
[V] Added "bin/internal/update_dart_sdk.sh merge=ours"
[D] [git 28184] C:\Users\hans\.puro\envs\t4c_old\flutter> git config merge.ours.driver rem
[D] [git 28184] finished with exit code 0 in 70ms
[D] [git 10232] C:\Users\hans\.puro\envs\t4c_old\flutter> git branch -u origin/beta beta
[D] git: branch 'beta' set up to track 'origin/beta'.
[D] [git 10232] finished with exit code 0 in 82ms
[V] Checking out beta / 1.20.2 / bbfbf1770c took 9328ms
[D] installEnvShims
[V] Started waiting for lock on C:\Users\hans\.puro\envs\t4c_old\flutter\bin\dart
[V] Waiting for lock on C:\Users\hans\.puro\envs\t4c_old\flutter\bin\dart took 0ms
[V] Started waiting for lock on C:\Users\hans\.puro\envs\t4c_old\flutter\bin\flutter
[V] Waiting for lock on C:\Users\hans\.puro\envs\t4c_old\flutter\bin\flutter took 0ms
[V] Started waiting for lock on C:\Users\hans\.puro\envs\t4c_old\flutter\bin\dart.bat
[V] Waiting for lock on C:\Users\hans\.puro\envs\t4c_old\flutter\bin\dart.bat took 0ms
[V] Started waiting for lock on C:\Users\hans\.puro\envs\t4c_old\flutter\bin\flutter.bat
[V] Waiting for lock on C:\Users\hans\.puro\envs\t4c_old\flutter\bin\flutter.bat took 0ms
[D] [git 22092] C:\Users\hans\.puro\envs\t4c_old\flutter> git update-index --assume-unchanged -- bin/dart bin/dart.bat bin/flutter bin/flutter.bat bin/internal/shared.bat bin/internal/shared.sh bin/internal/update_dart_sdk.ps1 bin/internal/update_dart_sdk.sh
[D] [git 22092] finished with exit code 0 in 187ms
[D] [git 24860] C:\Users\hans\.puro\envs\t4c_old\flutter> git config merge.ours.driver rem
[D] [git 24860] finished with exit code 0 in 72ms
[V] Saved 139ms by pre-caching engine
[V] Started waiting for lock on C:\Users\hans\.puro\prefs.json
[V] Waiting for lock on C:\Users\hans\.puro\prefs.json took 0ms
[D] flutterCache.engineVersion: null
[D] flutterConfig.engineVersion: 9d5b21729ff53dbf8eadd8bc97e0e30d77abec95
[V] Started waiting for lock on C:\Users\hans\.puro\envs\t4c_old\update.lock
[V] Waiting for lock on C:\Users\hans\.puro\envs\t4c_old\update.lock took 0ms
[V] Started waiting for lock on C:\Users\hans\.puro\envs\t4c_old\update.lock
[V] Waiting for lock on C:\Users\hans\.puro\envs\t4c_old\update.lock took 1ms
[V] Engine out of date
[V] Started checking if dart works
[D] > C:\Users\hans\.puro\shared\caches\9d5b21729ff53dbf8eadd8bc97e0e30d77abec95\dart-sdk\bin\dart.exe --version
[D] dart.exe finished in 42ms
[V] dart.exe: Dart SDK version: 2.9.1 (stable) (Wed Aug 12 12:37:19 2020 +0200) on "windows_x64"

[V] Checking if dart works took 43ms
[D] cacheExists: false
[D] cachePath: C:\Users\hans\.puro\envs\t4c_old\flutter\bin\cache
[D] resolvedPath: C:\Users\hans\.puro\envs\t4c_old\flutter\bin\cache
[D] isLink: false
[D] linkNeedsUpdate: false
[D] [git 11380] C:\Users\hans\.puro\envs\t4c_old\flutter> git rev-parse HEAD
[D] git: bbfbf1770cca2da7c82e887e4e4af910034800b6
[D] [git 11380] finished with exit code 0 in 70ms
[D] flutterCommit: bbfbf1770cca2da7c82e887e4e4af910034800b6
[V] Started waiting for lock on C:\Users\hans\.puro\envs\t4c_old\prefs.json
[V] Waiting for lock on C:\Users\hans\.puro\envs\t4c_old\prefs.json took 0ms
[V] Started waiting for lock on C:\Users\hans\.puro\envs\t4c_old\update.lock
[V] Waiting for lock on C:\Users\hans\.puro\envs\t4c_old\update.lock took 1ms
[V] Started waiting for lock on C:\Users\hans\.puro\envs\t4c_old\update.lock
[V] Waiting for lock on C:\Users\hans\.puro\envs\t4c_old\update.lock took 0ms
[V] Flutter tool out of date
[V] Started updating flutter tool
[D] [git 31376] C:\Users\hans\.puro\envs\t4c_old\flutter> git show HEAD:bin/internal/shared.sh
[D] [git 31376] finished with exit code 0 in 80ms
[D] C:\Users\hans\.puro\envs\t4c_old\flutter\packages\flutter_tools> C:\Users\hans\.puro\envs\t4c_old\flutter\bin\cache\dart-sdk\bin\pub.bat upgrade --no-precompile
[D] pub.bat finished in 2554ms
[D] pub.bat: Resolving dependencies...
    + _fe_analyzer_shared 5.0.0 (60.0.0 available)
    + analyzer 0.39.12 (5.12.0 available)
    + archive 2.0.13 (3.3.7 available)
    + args 1.6.0 (2.4.1 available)
    + async 2.4.2 (2.11.0 available)
    + boolean_selector 2.0.0 (2.1.1 available)
    + browser_launcher 0.1.7 (1.1.1 available)
    + build_daemon 2.1.4 (4.0.0 available)
    + built_collection 4.3.2 (5.1.1 available)
    + built_value 7.1.0 (8.5.0 available)
    + charcode 1.1.3 (1.3.1 available)
    + checked_yaml 1.0.2 (2.0.3 available)
    + collection 1.14.13 (1.17.2 available)
    + completion 0.2.2 (1.0.1 available)
    + convert 2.1.1 (3.1.1 available)
    + coverage 0.14.0 (1.6.3 available)
    + crypto 2.1.5 (3.0.3 available)
    + csslib 0.16.1 (0.17.2 available)
    + devtools 0.2.5 (2.9.4 available)
    + devtools_server 0.2.5 (2.9.4 available)
    + devtools_shared 0.2.5 (2.23.0 available)
    + dwds 5.0.0 (19.0.0 available)
    + file 5.2.1 (6.1.4 available)
    + file_testing 2.1.0 (3.0.0 available)
    + fixnum 0.10.11 (1.1.0 available)
    + flutter_template_images 1.0.1 (4.2.0 available)
    + glob 1.2.0 (2.1.1 available)
    + html 0.14.0+3 (0.15.3 available)
    + http 0.12.1 (0.13.6 available)
    + http_multi_server 2.2.0 (3.2.1 available)
    + http_parser 3.1.4 (4.0.2 available)
    + intl 0.16.1 (0.18.1 available)
    + io 0.3.4 (1.0.4 available)
    + js 0.6.2 (0.6.8 available)
    + json_annotation 3.0.1 (4.8.1 available)
    + logging 0.11.4 (1.1.1 available)
    + matcher 0.12.8 (0.12.16 available)
    + meta 1.1.8 (1.9.1 available)
    + mime 0.9.6+3 (1.0.4 available)
    + mockito 4.1.1 (5.4.0 available)
    + multicast_dns 0.2.2 (0.3.2+3 available)
    + mustache_template 1.0.0+1 (2.0.0 available)
    + native_stack_traces 0.3.7 (0.5.5 available)
    + node_interop 1.1.1 (2.1.0 available)
    + node_io 1.1.1 (2.2.0 available)
    + node_preamble 1.4.12 (2.0.2 available)
    + package_config 1.9.3 (2.1.0 available)
    + path 1.7.0 (1.8.3 available)
    + pedantic 1.9.0 (1.11.1 available)
    + petitparser 3.0.4 (5.4.0 available)
    + platform 2.2.1 (3.1.0 available)
    + pool 1.4.0 (1.5.1 available)
    + process 3.0.13 (4.2.4 available)
    + pub_semver 1.4.4 (2.1.4 available)
    + pubspec_parse 0.1.5 (1.2.3 available)
    + quiver 2.1.3 (3.2.1 available)
    + shelf 0.7.5 (1.4.1 available)
    + shelf_packages_handler 2.0.0 (3.0.2 available)
    + shelf_proxy 0.1.0+7 (1.0.3 available)
    + shelf_static 0.2.8 (1.1.2 available)
    + shelf_web_socket 0.2.3 (1.0.4 available)
    + source_map_stack_trace 2.0.0 (2.1.1 available)
    + source_maps 0.10.9 (0.10.12 available)
    + source_span 1.7.0 (1.10.0 available)
    + sse 3.5.0 (4.1.2 available)
    + stack_trace 1.9.5 (1.11.0 available)
    + stream_channel 2.0.0 (2.1.1 available)
    + stream_transform 1.2.0 (2.1.0 available)
    + string_scanner 1.0.5 (1.2.0 available)
    + sync_http 0.2.0 (0.3.1 available)
    + term_glyph 1.1.0 (1.2.1 available)
    + test 1.15.2 (1.24.2 available)
    + test_api 0.2.17 (0.5.2 available)
    + test_core 0.3.10 (0.5.2 available)
    + typed_data 1.2.0 (1.3.2 available)
    + usage 3.4.2 (4.1.1 available)
    + uuid 2.2.0 (3.0.7 available)
    + vm_service 4.1.0 (11.7.0 available)
    + watcher 0.9.7+15 (1.1.0 available)
    + web_socket_channel 1.1.0 (2.4.0 available)
    + webdriver 2.1.2 (3.0.2 available)
    + webkit_inspection_protocol 0.7.3 (1.2.0 available)
    + xml 4.2.0 (6.3.0 available)
    + yaml 2.2.1 (3.1.2 available)
    Changed 84 dependencies!
    84 packages have newer versions incompatible with dependency constraints.
    Try `pub outdated` for more information.

[V] Updating flutter tool took 2641ms
[V] Started compiling flutter tool
[D] > C:\Users\hans\.puro\envs\t4c_old\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev --verbosity=error --packages=C:\Users\hans\.puro\envs\t4c_old\flutter\packages\flutter_tools\.dart_tool\package_config.json --snapshot=C:\Users\hans\.puro\shared\flutter_tools\bbfbf1770cca2da7c82e887e4e4af910034800b6\flutter_tools.snapshot.tmp --no-enable-mirrors C:\Users\hans\.puro\envs\t4c_old\flutter\packages\flutter_tools\bin\flutter_tools.dart
[D] dart.exe finished in 58ms
[E] dart.exe: Setting VM flags failed: Unrecognized flags: verbosity

[V] Compiling flutter tool took 59ms
[x] Assertion failed: "C:\\Users\\hans\\.puro\\envs\\t4c_old\\flutter\\bin\\cache\\dart-sdk\\bin\\dart.exe subprocess failed with exit code 255"
    #0      runProcess (package:puro/src/process.dart:87)
    <asynchronous suspension>
    #1      setUpFlutterTool.<anonymous closure>.<anonymous closure> (package:puro/src/env/flutter_tool.dart:198)
    <asynchronous suspension>
    #2      ProgressNode.wrap (package:puro/src/progress.dart:68)
    <asynchronous suspension>
    #3      setUpFlutterTool.<anonymous closure> (package:puro/src/env/flutter_tool.dart:196)
    <asynchronous suspension>
    #4      checkAtomic.<anonymous closure> (package:puro/src/file_lock.dart:234)
    <asynchronous suspension>
    #5      lockFile (package:puro/src/file_lock.dart:68)
    <asynchronous suspension>
    #6      checkAtomic (package:puro/src/file_lock.dart:232)
    <asynchronous suspension>
    #7      setUpFlutterTool (package:puro/src/env/flutter_tool.dart:185)
    <asynchronous suspension>
    #8      createEnvironment (package:puro/src/env/create.dart:172)
    <asynchronous suspension>
    #9      CommandRunner.runCommand (package:args/command_runner.dart:212)
    <asynchronous suspension>
    #10     main (package:puro/src/cli.dart:234)
    <asynchronous suspension>

[x] Puro crashed! Please file an issue at https://github.com/PixelToast/puro
    Consider running the command with a higher log level: `--log-level=4`
```

**Comment by PixelToast** [comment]
Thanks for the bug report, this should be fixed in 1.2.6.
