### ISSUE TITLE
Puro crashes when specifying FLUTTER_STORAGE_BASE_URL

### ISSUE THREAD

**Issue by Vonarian** [PixelToast/puro#4]
With Puro v1.1.11, Puro got the ability to read FLUTTER_STORAGE_BASE_URL from system variables, but if there's one specified, Puro crashes:
```
PS C:\Users\Vonarian> puro upgrade stable --log-level=4
[D] FLUTTER_BIN: null
[D] Config: PuroConfig(
      gitExecutable: LocalFile: 'git',
      puroRoot: LocalDirectory: 'C:\Users\Vonarian\.puro',
      homeDir: LocalDirectory: 'C:\Users\Vonarian',
      projectDir: null,
      parentProjectDir: null,
      flutterGitUrl: https://github.com/flutter/flutter.git,
      engineGitUrl: https://github.com/flutter/engine.git,
      releasesJsonUrl: http://storage.flutterfarsi.ir,
      flutterStorageBaseUrl: https://storage.googleapis.com,
      environmentOverride: null,
      puroBuildsUrl: https://puro.dev/builds,
      buildTarget: PuroBuildTarget.windowsX64,
      enableShims: false,
    )
[V] Started waiting for lock on C:\Users\Vonarian\.puro\envs\stable\prefs.json
[V] Waiting for lock on C:\Users\Vonarian\.puro\envs\stable\prefs.json took 0ms
[x] Bad state: No element
    #0      _Array.last (dart:core-patch/array.dart:56)
    #1      PuroConfig.cachedReleasesJsonFile (package:puro/src/config.dart:235)
    #2      findFrameworkRelease (package:puro/src/env/releases.dart)
    #3      FlutterVersion.query (package:puro/src/env/version.dart:122)
    #4      EnvUpgradeCommand.run (package:puro/src/commands/env_upgrade.dart:66)
    <asynchronous suspension>
    #5      CommandRunner.runCommand (package:args/command_runner.dart:209)
    <asynchronous suspension>
    #6      main (package:puro/src/cli.dart:224)
    <asynchronous suspension>

[x] Puro crashed! Please file an issue at https://github.com/PixelToast/puro
```
Running ANY command that makes Puro use FLUTTER_STORAGE_BASE_URL crashes it, ls-versions, upgrade, create, etc.
In the previous version (1.1.10), we had to specify a mirror URL every time we were going to run one of the aforementioned commands, but I didn't run into this issue.
Checking the provided log, there seems to be some inconsistency in PuroConfig, it seems like `releaseJsonUrl` and `flutterStorageBaseUrl` use different values, even though I have specified one value for base URL: http://storage.flutterfarsi.ir
Googleapis is under sanctions here, therefore I can't use the default config.

**Comment by PixelToast** [comment]
This was fixed in 1.1.12
